PHOTOSHARE/PHOTOSHARE/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PHOTOSHARE.Models
{
    public class Album 
    {
        public int Id { get; set; }
        public string Owner { get; set; }
        public string Title { get; set; }
        public DateTime? Created { get; set; }
        public string Image { get; set; }
    }
}

PHOTOSHARE/PHOTOSHARE/Models/AlbumViewModel.cs
using Microsoft.EntityFrameworkCore;
using PHOTOSHARE.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PHOTOSHARE.Models
{
    public class AlbumViewModel 
    {

        public List<Album> MyAlbums { get; set; }
        public List<Album> SharedAlbums { get; set; }

        public Album Album { get; set; }

        public AlbumViewModel() { }

        public AlbumViewModel(PHOTOSHAREDBContext context, string userName)
        {
            MyAlbums = context.Albums.Where(a => a.Owner == userName).ToList();
            var albumIds = context.SharedAlbum.Where(s => s.SharedWith == userName).Select(a => a.AlbumId).ToList();
            SharedAlbums = context.Albums.Where(a => albumIds.Contains(a.Id)).ToList();
        }

        public static AlbumViewModel GetAlbum(PHOTOSHAREDBContext context, int albumId)
        {
            return new AlbumViewModel
            {
                Album = context.Albums.Where(a => a.Id == albumId).FirstOrDefault(),
            };

        }
    }
}

PHOTOSHARE/PHOTOSHARE/Models/album.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace PHOTOSHARE.Models
{
    public class Album 
    {
        public int Id { get; set; }
        public string Owner { get; set; }
        public string Title { get; set; }
        public DateTime? Created { get; set; }
        public string Image { get; set; }
    }
}

PHOTOSHARE/PHOTOSHARE/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Mvc;
using PHOTOSHARE.Data;
using PHOTOSHARE.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace PHOTOSHARE.Controllers
{
    public class AlbumController : Controller
    {
        private readonly PHOTOSHAREDBContext _context;

        public AlbumController(PHOTOSHAREDBContext context)
        {
            _context = context;
        }

        public ViewResult Index()
        {
            return View(new AlbumViewModel(_context, User.Identity.Name.ToString()));
        }

        public PartialViewResult CreateAlbum()
        {
            var albumViewModel = new AlbumViewModel();
            return PartialView("_AddEditAlbum", albumViewModel);
        }

        [HttpPost]
        public HttpStatusCode ShareAlbum(int albumId, string username)
        {
            var user = _context.Users.Where(u => u.UserName == username).FirstOrDefault();
            if (user != null && User.Identity.Name.ToString() != username)
            {
                try
                {
                    var shareAlbum = new SharedAlbum
                    {
                        AlbumId = albumId,
                        Owner = User.Identity.Name.ToString(),
                        SharedDate = DateTime.Now,
                        SharedWith = username,
                    };
                    _context.SharedAlbum.Add(shareAlbum);
                    _context.SaveChangesAsync();
                    return HttpStatusCode.OK;
                }
                catch (Exception)
                {
                    return HttpStatusCode.BadRequest;
                }
            }
            else
            {
                return HttpStatusCode.BadRequest;
            } 
                
            
        }

        public PartialViewResult EditAlbum(int albumId)
        {
            var albumViewModel = AlbumViewModel.GetAlbum(_context, albumId);
            return PartialView("_AddEditAlbum", albumViewModel);
        }

        [HttpPost]
        public HttpStatusCode EditAlbum(string title, string image, int id)
        {
            var album = _context.Albums.Where(a => a.Id == id).SingleOrDefault();

            try
            {
                album.Title = title;
                album.Image = String.IsNullOrEmpty(image) ? album.Image : image;
                _context.SaveChanges();
                return HttpStatusCode.OK;
            }
            catch (Exception)
            {
                return HttpStatusCode.BadRequest;
            }
        }

        [HttpPost]
        public HttpStatusCode CreateAlbum(string title, string image)
        {
            var album = new Album
            {
                Title = title,
                Owner = User.Identity.Name.ToString(),
                Created = DateTime.Now,
                Image = image,
            };
            try
            {
                _context.Albums.Add(album);
                _context.SaveChanges();
                return HttpStatusCode.OK;
            }
            catch (Exception)
            {
                return HttpStatusCode.BadRequest;
            }
        }

        [HttpPost]
        public HttpStatusCode DeleteAlbum(int Id)
        {
            var photos = _context.Photo.Where(p => p.AlbumId == Id).ToList();
            var sharedAlbums = _context.SharedAlbum.Where(s => s.AlbumId == Id).ToList(); 
            var album = _context.Albums.Where(a => a.Id == Id).FirstOrDefault();
            try
            {
                foreach(var photo in photos)
                {
                    _context.Photo.Attach(photo);
                    _context.Photo.Remove(photo);
                    _context.SaveChanges();
                }

                foreach (var sharedAlbum in sharedAlbums)
                {
                    _context.SharedAlbum.Attach(sharedAlbum);
                    _context.SharedAlbum.Remove(sharedAlbum);
                    _context.SaveChanges();
                }

                _context.Albums.Attach(album);
                _context.Albums.Remove(album);
                _context.SaveChanges();
                return HttpStatusCode.OK;
            }
            catch (Exception)
            {
                return HttpStatusCode.BadRequest;
            }
        }
    }
}

PHOTOSHARE/PHOTOSHARE/Controllers/PhotoController.cs
using Microsoft.AspNetCore.Mvc;
using PHOTOSHARE.Data;
using PHOTOSHARE.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace PHOTOSHARE.Controllers
{
    public class PhotoController : Controller
    {

        private readonly PHOTOSHAREDBContext _context;

        public PhotoController(PHOTOSHAREDBContext context)
        {
            _context = context;
        }

        public IActionResult Index(int albumId)
        {
            var vm = new PhotoViewModel(_context, albumId);
            return View(vm);
        }

        public PartialViewResult CreatePhoto()
        {
            var PhotoViewModel = new PhotoViewModel();
            return PartialView("_AddEditPhoto", PhotoViewModel);
        }

        public PartialViewResult EditPhoto(int PhotoId)
        {
            var vm = PhotoViewModel.GetPhoto(_context, PhotoId);
            return PartialView("_AddEditPhoto", vm);
        }

        [HttpPost]
        public HttpStatusCode EditPhoto(string title, string image, int id)
        {
            var Photo = _context.Photo.Where(a => a.Id == id).SingleOrDefault();


            try
            {
                Photo.Title = title;
                Photo.Image = String.IsNullOrEmpty(image) ? Photo.Image : image;
                _context.SaveChanges();
                return HttpStatusCode.OK;
            }
            catch (Exception)
            {
                return HttpStatusCode.BadRequest;
            }
        }

        [HttpPost]
        public HttpStatusCode CreatePhoto(string title, int albumId, string image)
        {
            var Photo = new Photo
            {
                Title = title,
                AlbumId = albumId,
                Image = image,
                Created = DateTime.Now
            };
            try
            {
                _context.Photo.Add(Photo);
                _context.SaveChanges();
                return HttpStatusCode.OK;
            }
            catch (Exception e)
            {
                return HttpStatusCode.BadRequest;
            }
        }

        [HttpPost]
        public HttpStatusCode DeletePhoto(int Id)
        {
            var Photo = _context.Photo.Where(a => a.Id == Id).FirstOrDefault();
            try
            {
                _context.Photo.Attach(Photo);
                _context.Photo.Remove(Photo);
                _context.SaveChanges();
                return HttpStatusCode.OK;
            }
            catch (Exception)
            {
                return HttpStatusCode.BadRequest;
            }
        }
    }
}

PHOTOSHARE/PHOTOSHARE/Views/Album/Index.cshtml
@model AlbumViewModel

@{
    ViewData["Title"] = "Albums";
}

<link rel="stylesheet" href="./css/Album.css">
<link rel="stylesheet" href="./lib/bootstrap/dist/css/bootstrap.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css"
      integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g=="
      crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">

<h1>Albums</h1>

<button id="btnAddAlbum" class="btn btn-primary">Add Album</button>
<br />

<input type="hidden" value="@Url.Action("CreateAlbum", "Album")" id="createAlbumUrl" />
<input type="hidden" value="@Url.Action("DeleteAlbum", "Album")" id="deleteAlbumUrl" />
<input type="hidden" value="@Url.Action("EditAlbum", "Album")" id="editAlbumUrl" />

<div class="my-4 row">
    @if (Model.MyAlbums.Any())
    {
        foreach (var album in Model.MyAlbums)
        {
            <div class="col-md-4 m-4 py-3 photo-container">
                <a class="p-3">@album.Title</a>
                <img src="@album.Image" class="img-fluid rounded p-2" alt="@album.Owner">
                <div class="row justify-content-between p-2 actionButtons">
                    <a id="edit"
                       class="btn btn-light btn-sm edit"
                       data-id="@album.Id">
                        <i class="bi bi-pencil"></i> Edit
                    </a>
                    <a id="view" class="btn btn-light btn-sm" href="@Url.Action("Index", "Photo", new { albumId = album.Id })"><i class="bi bi-eye-fill"></i> View</a>
                    <a id="delete"
                       class="btn btn-light btn-sm delete"
                       data-url="@Url.Action("DeleteAlbum", "Album", new { id = @album.Id })">
                        <i class="bi bi-trash"></i> Delete
                    </a>
                    <a id="share" class="btn btn-light btn-sm share" data-id="@album.Id"><i class="bi bi-share"></i> Share</a>
                </div>
            </div>
        }

    }
    else
    {
        <div class="alert alert-primary" role="alert">
            You have no Albums!
        </div>
    }
</div>


<h1>Shared With Me</h1>

<div class="my-4 row">
    @if (Model.SharedAlbums.Any())
    {
        foreach (var album in Model.SharedAlbums)
        {
            <div class="col-md-4 m-4 py-3 photo-container">
                <a class="p-3">@album.Title</a>
                <img src="@album.Image" class="img-fluid rounded p-2" alt="@album.Owner">
                <div class="row justify-content-between p-2 actionButtons">
                    <a id="view" class="btn btn-light btn-sm" href="@Url.Action("Index", "Photo", new { albumId = album.Id })"><i class="bi bi-eye-fill"></i> View</a>
                </div>
            </div>
        }

    }
    else
    {
        <div class="alert alert-primary my-4" role="alert">
            No Albums shared with you!
        </div>
    }
</div>
<br />

<div class="modal" role="dialog" id="createAlbumModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create new Album</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="submit">Save</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" role="dialog" id="deleteAlbumModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Album</h5>
            </div>
            <div class="modal-body">
                Are you Sure you want to delete the album?
            </div>
            <div class="modal-footer">
                <button id="deleteAlbum" type="button" class="btn btn-primary">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" role="dialog" id="shareAlbumModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Share Album</h5>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="username">Share With User</label>
                    <input data-url="@Url.Action("ShareAlbum", "Album")" type="text" id="username" class="form-control" required />
                </div>
            </div>
            <div class="modal-footer">
                <button id="shareAlbum" type="button" class="btn btn-primary">Share</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div id="snackbar" class="snackbar"></div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"
        integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript">
    $(document).ready(function () {
        debugger;

        $('.share').on('click', function () {
            $('#shareAlbumModal').modal('show');
            $('#username').attr('data-id', $('#share').data('id'));
            $('#shareAlbum').on('click', function () {
                debugger;
                var username = $('#username').val();
                var url = $('#username').data('url');
                var albumId = $('#username').data('id');
                $.post(url, { albumId, username }, function (response) {
                    if (response === 200)
                        showToastr('Album Shared!', false);
                    else
                        showToastr('Album could not share! Ensure Username is entered correctly.', true);
                    $('#shareAlbumModal').modal('hide');
                });
            });
        });

        $('.edit').on('click', function () {
            debugger;
            let url = $('#editAlbumUrl').val();
            let albumId = $(this).data('id');
            $.get(url, { albumId }, function (response) {
                $('.modal-body').html(response);
                $('#createAlbumModal').modal('show');
            })
        })

        $('#btnAddAlbum').on('click', function () {
            var url = $('#createAlbumUrl').val();
            $.get(url, function (response) {
                $('.modal-body').html(response);
                $('#createAlbumModal').modal('show');
            });
        });

        $('#submit').on('click', () => {
            var reader = new FileReader();
            var file = document.querySelector('input[type=file]').files[0];;

            if (file) {
                reader.readAsDataURL(file);
            }
            else {
                var albumId = $('#Album_Id').val();
                if (albumId > 0)
                    EditAlbum(null, albumId);
            }

            reader.onload = function (e) {
                var image = reader.result;
                var albumId = $('#Album_Id').val();
                if (albumId > 0)
                    EditAlbum(image, albumId);
                else
                    CreateAlbum(image);
            };
        });

        $('.delete').on('click', function () {
            debugger;
            let url = $(this).data('url');
            $('#deleteAlbumModal').modal('show');
            $('#deleteAlbumModal #deleteAlbum').attr('data-url', url);
            document.getElementById('deleteAlbum').addEventListener('click', function (event) {
                const { url } = event.currentTarget.dataset;
                $.post(url, function () {
                    $('#deleteAlbumModal').modal('hide');
                    showToastr('Album Deleted!', false);
                    window.location.reload();
                }).fail(function () {
                    showToastr('Album cannot be Deleted!', true);
                })
            })
        });

    })

    function EditAlbum(image, id) {
        var url = $('#createAlbumModal #url').val();
        var title = $('#title').val();
        image = image ?? '';

        $.post(url, { title, image, id }, function () {
            $('#createAlbumModal').modal('hide');
            $('.modal-body').html();
            showToastr('Album Updated!', false);
            window.location.reload();
        });
    }

    function CreateAlbum(image) {
        var url = $('#createAlbumModal #url').val();
        var title = $('#title').val();

        $.post(url, { title, image }, function () {
            $('#createAlbumModal').modal('hide');
            $('.modal-body').html();
            showToastr('Album Created!', false);
            window.location.reload();
        });
    }

    function showToastr(text, fail) {
        if (!fail)
            toastr['success'](text);
        else
            toastr['error'](text);

        toastr.options = {
            'newestOnTop': false,
            'progressBar': false,
            'positionClass': 'toast-top-right',
            'preventDuplicates': false,
            'showDuration': '300',
            'hideDuration': '1000',
            'timeOut': '5000',
            'extendedTimeOut': '1000',
            'showEasing': 'swing',
            'hideEasing': 'linear',
            'showMethod': 'fadeIn',
            'hideMethod': 'fadeOut'
        };
    }

</script>

PHOTOSHARE/PHOTOSHARE/Views/Album/_AddEditAlbum.cshtml
@model AlbumViewModel

@Html.HiddenFor(a => a.Album.Id)
@if (Model.Album != null)
{
    <input type="hidden" id="url" value="@Url.Action("EditAlbum", "Album")" />
    <div class="form-group">
        <label for="title">Album Title</label>
        <input id="title" asp-for="Album.Title" class="form-control" />
    </div>
    <div class="form-group">
        <label for="photo">Select a Photo</label>
        <input type="file" class="form-control-file" id="photo" asp-for="Album.Image">
    </div>
}
else
{
    <input type="hidden" id="url" value="@Url.Action("CreateAlbum", "Album")" />

    <div class="form-group">
        <label for="title">Album Title</label>
        <input id="title" asp-for="Album.Title" class="form-control" required />
    </div>
    <div class="form-group">
        <label for="photo">Select a Photo</label>
        <input type="file" class="form-control-file" id="photo" asp-for="Album.Image" required>
    </div>
}